cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path("add_to_cart/<int:product_id>", views.add_to_cart, name="add_to_cart"),
    path("remove/<int:cart_item_id>", views.remove_from_cart, name="remove_from_cart"),
    path("remove_all/<int:cart_item_id>", views.remove_all_from_cart, name="remove_all_from_cart"),
    path("cart", views.cart_details, name="cart_detail"),
    path('checkout', views.checkout, name = 'checkout'),
    
    # path('checkout', views.CheckoutView.as_view(), name = 'checkout'),
]

home/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
from . import views

app_name = 'home'

urlpatterns = [
    # path('', views.home, name = 'home'),
    path('', views.HomeView.as_view(), name = 'home'),
    path('contact', views.MyFormView.as_view(), name = 'contact'),


    path('product/<int:product_id>/', views.ProductView.as_view(), name='productview'),

    # path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
]

shop/urls.py
# Link of video used - https://www.youtube.com/watch?v=7VEveJz7hdM&t=4022s

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('useraccess.urls')),
    path('', include('cart.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.shortcuts import reverse



# class Category(models.Model):
#     name = models.CharField(max_length=100)


# Create your models here.
CATEGORY = (
    ('Cake', 'Cake'),
    ('Ice Cream', 'Ice cream'),
    ('Shake', 'Shake'),
)

class Product(models.Model):
    product_name = models.CharField(max_length=100, blank=True)
    category = models.CharField(choices=CATEGORY, max_length=10)
    subcategory = models.CharField(max_length=100, blank=True)
    price = models.IntegerField(default=0)
    desc = models.CharField(max_length=300, blank=True)
    image = models.ImageField(upload_to='images')
    id = models.BigAutoField(primary_key=True, serialize=False)

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse("cart:add_to_cart", kwargs= {"product_id" : self.pk})

    def get_add_to_cart_url(self):
        return reverse("cart:add_to_cart", kwargs= {"product_id": self.pk})

    def get_remove_from_cart_url(self):
        return reverse("cart:remove_from_cart", kwargs= {"product_id": self.pk})

    def get_remove_all_from_cart_url(self):
        return reverse("cart:remove_all_from_cart", kwargs= {"product_id": self.pk})


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length = 12)
    message = models.TextField()

    def __str__(self):
        return self.name
    

home/forms.py
from django import forms 
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'message']

home/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from home.models import Product
from math import ceil
from .forms import ContactForm
from django.views.generic.edit import FormView

from django.views.generic import DetailView, ListView, View

# Create your views here.
class HomeView(ListView):
    model = Product
    template_name = "index2.html"
    context_object_name = 'product'

# def home(request):
#     all_products = Product.objects.all()
#     n = len(all_products)
#     items_per_row = 3
#     nSlides = n // items_per_row + ceil((n / items_per_row) - (n // items_per_row))
#     allProds = [all_products[i:i + items_per_row] for i in range(0, n, items_per_row)]
#     params = {'allProds': allProds, 'nSlides': range(1, nSlides + 1), 'items_per_row': items_per_row}

#     return render(request, 'index.html', params)


class ProductView(DetailView):
    model = Product
    template_name = "product.html"
    context_object_name = 'product'

    def get_object(self, queryset=None):
        product_id = self.kwargs.get('product_id')
        return get_object_or_404(Product, id=product_id)


class MyFormView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = '/contact'


    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Your message has been sent")
        return super().form_valid(form) 

home/templates/base.html
<!-- If the CSS stops working, troubleshoot is at 3:04:26 of video -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>
    {% block title %}    {% endblock title %}
  </title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static '/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static '/assets/css/style.css' %}" rel="stylesheet">


</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center justify-content-between">

      <!--<h1 class="logo"><a href="/">HIJKL</a></h1>-->
      <!-- Uncomment below if you prefer to use an image logo -->
      <a href="/" class="logo"><img src="{% static '/assets/img/logo.png' %}" alt="" class="img-fluid">Erilicious</a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="/">Home</a></li>
          <li><a class="nav-link scrollto" href="#">Blog</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>

          {% if request.user.is_authenticated %}
          <li><a class="nav-link scrollto" href="/checkout">Checkout</a></li>
          {% endif %}

          <li><a class="nav-link scrollto bg-danger py-2 px-3" href="/cart">Cart</a></li>
          
          
          

          {% if request.user.is_authenticated %}

          <li><a class="nav-link scrollto " href="/logout">Logout</a></li>
          
          {% else %}

          <li class="dropdown"><a href="#"><span>Signin</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="/signup">Signup</a></li>
              <li><a href="/login">Login</a></li>
              
            </ul>
          </li>

          {% endif %}
          

          
          <li><a class="nav-link scrollto bg-dark py-2 px-3" href="/contact">Contact</a></li>

        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero">
    
    {% block content %}


    {% endblock content %}

  </section><!-- End Hero -->

  <main id="main">


    {% block body %}
    
    {% endblock body %}
    

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Tempo</h3>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Tempo</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/tempo-free-onepage-bootstrap-theme/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <a href="{% url "logout" %}">Logout</a>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static '/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static '/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static '/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static '/assets/vendor/php-email-form/validate.js' %}"></script>
  
  <!-- Template Main JS File -->
  <script src="{% static '/assets/js/main.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

 
</body>

</html>

home/templates/contact.html
{% extends "base.html" %}

{% block title %}
Contact
{% endblock title %}

{% block content %}



<div class="hero-container">
    <div class="card bg-light p-5">

        {% for message in messages %} 
    
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    
        {% endfor %}

        <h1 align="center" style="color: black;">Connect With Us</h1>
        <hr>
        <form method="post">
            {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <button type="submit">Send Message</button>
        </form>



    </div>
</div>
{% endblock content %}

home/templates/index.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock title %}

{% block content %}
<div class="hero-container">
  <h3>Welcome to <strong>Shopping Cart</strong></h3>
  <h1>Erilicious</h1>
  <h2>We are team of talented designers making websites with Bootstrap</h2>
  <a href="#about" class="btn-get-started scrollto">Get Started</a>
</div>
{% endblock content %}


{% block body %}

{% load static %}

<!-- ======= Portfolio Section ======= -->
<section id="portfolio" class="portfolio">
  <div class="container">

    <div class="section-title">
      <h2>Welcome to Erilicious</h2>
      <h3>Check out our <span>Products</span></h3>
    </div>


    {% comment %} {% for product, range, nSlides %}

    <h3 class="my-3 text-center text-success bg-light">
      {{product.0.category}} Flashsale
    </h3>

    <div class="container">
      <div class="row">

        {% for i in product %}

        <div class="col-md-3 mt-3">
          <img src="/media/{{i.image}}" class="card-img-top" alt="not found" height="200px" width="150px" />
          <div class="card-body">
            <h5 class="card-title mt-2" id="namepr{{i.id}}">{{i.product_name}}</h5>
            <p class="card-text">{{i.desc|slice:"0:53"}}...</p>
            <h6 class="card-title mb-3">
              Price:<span id="pricepr{{i.id}}">{{i.price}}</span>
            </h6>
            <span id="divpr{{i.id}}" class="divpr">
              <button id="pr{{i.id}}" class="btn btn-danger cart btn-sm mt-0">
                AddToCart
              </button>
            </span>

            <a href="/media/{{i.image}}">
              <button class="btn btn-dark btn-sm cart">View</button></a>
          </div>
        </div>

        {% endfor %}

      </div>
    </div>

    {% endfor %} {% endcomment %}

    {% for product_set in allProds %}

    <div class="container">
      <div class="row">

        {% for product in product_set %}

        <div class="col-md-4 mt-3">
          <img src="/media/{{ product.image }}" class="card-img-top" alt="not found" height="300px" width="100px" />
          <div class="card-body">
            <h5 class="card-title mt-3" id="namepr{{ product.id }}">{{ product.product_name }}</h5>
            <p class="card-text">{{ product.desc|slice:"0:53" }}...</p>
            <h6 class="card-title mb-3">
              Price: <span id="pricepr{{ product.id }}">{{ product.price }}</span>
            </h6>
            <span id="divpr{{ product.id }}" class="divpr">
              <a href = "{% url 'cart:add_to_cart' product.id %}"><button id="pr{{ product.id }}" class="btn btn-danger cart btn-sm mt-0">AddToCart</button></a>
            </span>

            {% comment %} <a href="/media/{{ product.image }}"><button class="btn btn-dark btn-sm cart">View</button></a> {% endcomment %}
            <a href="{% url 'home:productview' product.id %}"><button class="btn btn-dark btn-sm cart">View</button></a>
          </div>
        </div>

        {% endfor %}
      </div>
    </div>

{% endfor %}



  </div>
</section>

<!-- End Portfolio Section -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>



{% endblock body %}

home/templates/index2.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock title %}

{% block content %}
<div class="hero-container">
  <h3>Welcome to <strong>Shopping Cart</strong></h3>
  <h1>Erilicious</h1>
  <h2>We are team of talented designers making websites with Bootstrap</h2>
  <a href="#about" class="btn-get-started scrollto">Get Started</a>
</div>
{% endblock content %}


{% block body %}

{% load static %}




<main>
    <div class="container">


      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for product in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" alt=""> {% endcomment %}
                <img src="/media/{{ product.image }}" class="card-img-top" alt="not found" height="300px" width="100px" />
                  <a href="{{ product.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->
              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <h5>
                    <strong>
                      <a href="{% url 'home:productview' product.id %}" class="dark-grey-text">{{ product.product_name }}</a>
                    </strong>
                  </h5>
                  
                  <h5 class="grey-text">{{ product.get_category_display }}</h5>
                  <span id="divpr{{ product.id }}" class="divpr">
                    <a href = "{% url 'cart:add_to_cart' product.id %}"><button id="pr{{ product.id }}" class="btn btn-success cart btn-sm mt-0">AddToCart</button></a>
                  </span>
             
              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->

          {% endfor %}
         
        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

    </div>
  </main>

<!-- End Portfolio Section -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>



{% endblock body %}

home/templates/product.html
{% extends "base.html" %}
{% block content %}
<div class="hero-container">

    <div class="card bg-light p-5">

        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6">
                    <img src="/media/{{ product.image }}" class="card-img-top" alt="not found" height="300px" width="300px" />
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title mt-3" id="namepr{{ product.id }}">{{ product.product_name }}</h5>
                        <p class="card-text">{{ product.category }}</p>
                        <p class="card-text">{{ product.subcategory }}</p>
                        <p class="card-text">{{ product.desc }}</p>
                        <h6 class="card-title mb-3">
                            Price: <span id="pricepr{{ product.id }}">{{ product.price }}</span>
                        </h6>
                        <span id="divpr{{ product.id }}" class="divpr">
                            <a href="{% url 'home:productview' product.id %}">
                                <button id="pr{{ product.id }}"
                                    class="btn btn-success cart btn-sm mt-0">AddToCart</button>
                            </a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>

{% endblock %}