cart/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path("add_to_cart/<int:product_id>", views.add_to_cart, name="add_to_cart"),
    path("remove/<int:cart_item_id>", views.remove_from_cart, name="remove_from_cart"),
    path("remove_all/<int:cart_item_id>", views.remove_all_from_cart, name="remove_all_from_cart"),
    path("cart", views.cart_details, name="cart_detail"),
    path('checkout', views.checkout, name = 'checkout'),
    
    # path('checkout', views.CheckoutView.as_view(), name = 'checkout'),
]

shop/urls.py
# Link of video used - https://www.youtube.com/watch?v=7VEveJz7hdM&t=4022s

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('useraccess.urls')),
    path('', include('cart.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from home.models import Product
from django.utils import timezone

# Create your models here.

# original 
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product}"

    def get_absolute_url(self):
        return reverse("cart:cart_detail", kwargs={})


class Checkout(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length = 12)
    address = models.CharField(max_length= 200)
    code = models.IntegerField()

    def __str__(self):
        return self.user.email
    





    """
class OrderProduct(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.product.product_name}"

    def get_total_product_price(self):
        return self.quantity * self.product.price 
"""


"""
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(OrderProduct)
    ordered_date = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    checkout = models.ForeignKey('Checkout', on_delete=models.SET_NULL, blank = True, null = True)

    def __str__(self):
        return self.user.email 

    def get_total_price(self):
        total = 0
        for order_product in self.products.all():
            total += order_product.get_total_product_price()
        return 
"""

"""
# trial
class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(OrderProduct)
    ordered_date = models.DateTimeField(default=timezone.now)
    ordered = models.BooleanField(default=False)
    checkout = models.ForeignKey('Checkout', on_delete=models.SET_NULL, blank = True, null = True)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product}"

    def get_total_price(self):
        total = 0
        for order_product in self.products.all():
            total += order_product.get_total_product_price()
        return total

    def get_absolute_url(self):
        return reverse("cart:cart_detail", kwargs={})

"""

cart/forms.py
from django import forms 

class CheckoutForm(forms.Form):
    
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Phone Number'
    }))
    
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Address'
    }))
    
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ZIP Code'
    }))

    save_info = forms.BooleanField(required = False)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from cart.models import Cart, Checkout
from home.models import Product
from django.db.models import Sum
from datetime import datetime
from django.views.generic import View
from .forms import CheckoutForm

# Create your views here.

#Original
@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart_item = Cart.objects.filter(user=request.user, product=product).first()

    if cart_item:
        cart_item.quantity += 1
        cart_item.save()
        messages.success(request, "Item added to your cart.")
    else:
        Cart.objects.create(user=request.user, product=product)
        messages.success(request, "Item added to your cart.")

    return redirect("/cart")


@login_required
def remove_from_cart(request, cart_item_id):
    cart_item = get_object_or_404(Cart, id=cart_item_id)

    if cart_item.user == request.user:

            if cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
                messages.success(request, "Item deleted from your cart.")

            else:
                cart_item.delete()
                messages.success(request, "Item deleted from your cart.")


    return redirect("/cart")


@login_required
def remove_all_from_cart(request, cart_item_id):
    cart_item = get_object_or_404(Cart, id=cart_item_id)

    if cart_item.user == request.user:
        cart_item.delete()
        messages.success(request, "Item deleted from your cart.")

    return redirect("/cart")


@login_required
def cart_details(request):
    cart_items = (Cart.objects.filter(user=request.user).select_related('product'))
    total_price = sum(item.quantity * item.product.price for item in cart_items)

    for item in cart_items:
        item.total_item_price = item.quantity * item.product.price

    total_items = cart_items.aggregate(total_items=Sum('quantity'))['total_items'] or 0

    context = {
        "cart_items": cart_items,
        "total_price": total_price,
        "total_items": total_items,
    }

    return render(request, "cart_details.html", context)


# original
def checkout(request):
    cart_items = (Cart.objects.filter(user=request.user).select_related('product'))
    total_price = sum(item.quantity * item.product.price for item in cart_items)

    for item in cart_items:
        item.total_item_price = item.quantity * item.product.price

    total_items = cart_items.aggregate(total_items=Sum('quantity'))['total_items'] or 0

    context = {
        "cart_items": cart_items,
        "total_price": total_price,
        "total_items": total_items,
    }

    if request.method == "POST":
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        code = request.POST.get('code')
        user = request.user
        checkout_details = Checkout(user=user, phone=phone, address=address, code=code)
        checkout_details.save()
        messages.success(request, "Your order has been placed")

    return render(request, "checkout.html", context)





"""
# trial

class CheckoutView(View):
    def get(self, *args, **kwargs):
        form = CheckoutForm()
        cart = Cart.objects.get(user=self.request.user, ordered=False)
        context = {
            'form': form,
            'cart': cart
        }
        return render(self.request, 'checkout2.html', context)

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)

        try:
            cart = Cart.objects.get(user=self.request.user,ordered = False)
            if form.is_valid():
                phone = form.cleaned_data.get('phone')
                address = form.cleaned_data.get('address')
                code = form.cleaned_data.get('code')

                checkout_details = Checkout( user = self.request.user, phone=phone, address=address, code=code)
                checkout_details.save()
                cart.checkout_details = checkout_details
                cart.save()
                messages.success(request, "Your order has been placed")
                
            return redirect('/')

        except ObjectDoesNotExist:
            messages.error(self.request, "You do not have an order")
            return redirect('/')
"""

"""
#Trial
@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart_product, created = OrderProduct.objects.get_or_create(product = product, user=request.user, ordered=False)
    cart_qs = Cart.objects.filter(user=request.user, ordered= False)

    if cart_qs.exists():
        cart = cart_qs[0]

        if cart.products.filter(product__product_id=product.product_id).exists():
            cart_item.quantity += 1
            cart_item.save()
            messages.success(request, "Item added to your cart.")
    
        else:
            cart.products.add(order_item)
            messages.success(request, "Item added to your cart.")
            return redirect("/cart")

    else:
        ordered_date = timezone.now()
        cart = Cart.objects.create(user=request.user, ordered_date = ordered_date)
        cart.items.add(order_item)
        messages.success(request, "Item added to your cart.")
    return redirect("/cart")
"""

cart/templates/cart_details.html
{% extends "base.html" %}

{% block title %}
Cart
{% endblock title %}


{% block content %}

<div class="hero-container">

    <div class="card bg-light p-5">

        {% for message in messages %} 
    
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    
        {% endfor %}


        {% if cart_items %}
        <table class="table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total Price</th>
                    <th>Remove 1</th>
                    <th>Remove all</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>{{ item.product.product_name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.product.price }}</td>
                    <td>{{ item.total_item_price }}</td>
                    <td><a href="{% url 'cart:remove_from_cart' item.id %}">Remove 1</a></td>
                    <td><a href="{% url 'cart:remove_all_from_cart' item.id %}">Remove all</a></td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4"></td>
                    <td>Total:</td>
                    <td>{{ total_price }}</td>
                </tr>
            </tfoot>
        </table>

        <a href="/checkout" class="btn btn-primary">Checkout</a>
        {% else %}
        <p>Your shopping cart is empty.</p>
        {% endif %}

    </div>
  
    
</div>
{% endblock content %}

cart/templates/checkout.html
{% extends "base.html" %}

{% block title %}
Cart
{% endblock title %}


{% block content %}

<div class="hero-container">

    <div class="card bg-light p-5">

        <p><strong>Review your order</strong></p>

        {% for message in messages %} 
    
        <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
          <strong>{{message}}</strong>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    
        {% endfor %}


        {% if cart_items %}
        <table class="table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total Price</th>
                    <th>Remove 1</th>
                    <th>Remove all</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart_items %}
                <tr>
                    <td>{{ item.product.product_name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.product.price }}</td>
                    <td>{{ item.total_item_price }}</td>
                    <td><a href="{% url 'cart:remove_from_cart' item.id %}">Remove 1</a></td>
                    <td><a href="{% url 'cart:remove_all_from_cart' item.id %}">Remove all</a></td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="4"></td>
                    <td>Total:</td>
                    <td>{{ total_price }}</td>
                </tr>
            </tfoot>
        </table>

        <form method="post" action="/checkout">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Phone Number</label>
                <input type="text" class="form-control" id="phone" name = "phone" placeholder="Enter your Phone Number">
            </div>
            <div class="form-group py-2">
                <label for="name">Address</label>
                <input type="text" class="form-control" id="address" name = "address" placeholder="Enter your Address">
            </div>
            <div class="form-group py-2">
                <label for="name">Zip Code</label>
                <input type="text" class="form-control" id="code" name = "code" placeholder="Enter your ZIP Code">
            </div>
            <button class = "btn btn-primary py-2" type="submit">Place Order</button>
        </form>

        
        {% else %}
        <p>Your shopping cart is empty.</p>
        {% endif %}

    </div>
  
    
</div>
{% endblock content %}